#!/usr/bin/env bash
set -euo pipefail

function up() {
    option=$1
    if [[ "$OSTYPE" == "linux-gnu"* ]]; then # Linux
        xhost +local:root || echo "Cannot connect to display. Run headless."
    elif [[ "$OSTYPE" == "darwin"* ]]; then # Mac OSX
        ip=$(ifconfig en0 | grep inet | awk '$1=="inet" {print $2}')
        echo "DISPLAY=$ip:0" >.display
        xhost + $ip
    else
        printf "Unknown OS detected."
        exit 1
    fi
    case $option in
    -b | --build)
        COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker compose up --pull never --build
        ;;
    -p | --pull)
        COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker compose up --pull missing --no-build
        ;;
    *)
        printf "usage: crs-docker up [-b/-p]\n"
        printf "\noptions:\n\n"
        printf "    -b | --build:    Always builds crs image from source.\n"
        printf "    -p | --pull:     Pull crs image from repository.\n"
        exit 1
        ;;
    esac
    shift
}

function down() {
    docker compose down
    if [[ "$OSTYPE" == "linux-gnu"* ]]; then # Linux
        xhost -local:root
    elif [[ "$OSTYPE" == "darwin"* ]]; then # Mac OSX
        ip=$(ifconfig en0 | grep inet | awk '$1=="inet" {print $2}')
        xhost - $ip
        if [ -f .display ]; then
            rm .display
        fi
    else
        printf "Unknown OS detected."
        exit 1
    fi
}

function run() {
    docker compose run --service-ports crs # still needs some refining!
}

function clean() {
    docker system prune
    docker image rm registry.ethz.ch/ics/crs
}

function attach() {
    n_running=$(docker ps | grep crs | wc -l | xargs)
    if [ "${n_running}" -eq 0 ]; then
        printf "There are no CRS container running.\n\n"
        usage
    elif [ "${n_running}" -eq 1 ]; then
        container_id=$(docker ps | grep crs | awk '{print $1}')
        printf "Attaching to container with ID: ${container_id}\n"
        docker exec -it ${container_id} bash
    else
        printf "There are multiple CRS container running. Stop all but one.\n"
    fi
}

function pwd_is_root() {
    if [[ -f Dockerfile && -f .dockerignore ]]; then
        true
    else
        false
    fi
}

function usage() {
    printf "usage: crs-docker <command> [-h]\n"
    printf "\nthere are the following commands:\n\n"
    printf "    up [-b/-p]:  Starts docker container with CRS environment.\n"
    printf "                 -b | --build: build CRS Docker image from scratch.\n"
    printf "                 -p | --pull: pull CRS Docker image from registry.\n"
    printf "    down:        Shuts down docker container.\n"
    printf "    run:         Open interactive shell in container.\n"
    printf "    clean:       Delete the previously built Docker image. 'crs-docker up' will rebuild the image.\n"
    printf "    attach:      Attach to a running container (only works for a single running container).\n"
}
if [[ -z "${1-}" ]]; then
    usage
    exit 0
fi

while [[ -n "${1-}" ]]; do
    if ! $(pwd_is_root); then
        printf "Cannot run docker in this folder! Change to the highest-level CRS folder.\n"
        exit 1
    fi

    case $1 in
    up)
        up "${2---build}"
        shift
        ;;
    down) down ;;
    run) run ;;
    clean) clean ;;
    attach) attach ;;
    -h | --help)
        usage
        exit 0
        ;;
    *)
        usage
        exit 1
        ;;
    esac
    shift
done
