image: registry.ethz.ch/ics-group/projects/andrea/crs-2.0:dev


### =============================================================
### ================     BUILD STAGE    =========================
### =============================================================

build all: # build CRS inside docker image
  stage: build
  script:
    - crs init
    - catkin build
  retry: 0
  tags:
    - deep-thought

build without kinematic: # build CRS inside docker image
  stage: build
  script:
    - crs init
    - catkin clean
    - catkin config --skiplist kinematic_model kinematic_sensor_model
    - catkin build
  retry: 0
  tags:
    - deep-thought

build without lowpass: # build CRS inside docker image
  stage: build
  script:
    - crs init
    - catkin clean
    - catkin config --skiplist lowpass_estimator
    - catkin build
  retry: 0
  tags:
    - deep-thought

build only mpc controller: # build CRS inside docker image
  stage: build
  script:
    - crs init
    - catkin clean
    - catkin config --skiplist ff_fb_controller pid_controller
    - catkin build
  retry: 0
  tags:
    - deep-thought

build only pid controller: # build CRS inside docker image
  stage: build
  script:
    - crs init
    - catkin clean
    - catkin config --skiplist ff_fb_controller mpc_controller
    - catkin build
  retry: 0
  tags:
    - deep-thought

### =============================================================
### ================     TEST STAGE    =========================
### =============================================================
test without ros: # build CRS inside docker image
  stage: test
  script:
    - crs init
    - touch src/ros4crs/CATKIN_IGNORE # Do not build or test the ros packages
    - mkdir devel
    - mkdir devel/include
    - catkin clean --yes
    - catkin build
    - catkin run_tests --jobs=1 
  retry: 1
  tags:
    - deep-thought
