# Description of configuration files can be found at "https://gitlab.ethz.ch/ics-group/projects/andrea/crs-2.0/-/wikis/ros-configuration"
# initial state
initial_state:
  type: "pacejka_car_state"
  value: [0, 0, 0, 1, 0, 0] 

# initial P (state covariance matrix)
P_init: [[1, 0, 0, 0, 0, 0],
         [0, 1, 0, 0, 0, 0], 
         [0, 0, 1, 0, 0, 0], 
         [0, 0, 0, 1, 0, 0], 
         [0, 0, 0, 0, 1, 0], 
         [0, 0, 0, 0, 0, 1]]

#
model_dynamics:
  # type describes what type of model we want to use / should be loaded
  type: "pacejka_discrete"

  # Q (process noise covariance matrix)
  Q: [[1, 0, 0, 0, 0, 0],
      [0, 1, 0, 0, 0, 0], 
      [0, 0, 1, 0, 0, 0], 
      [0, 0, 0, 1, 0, 0], 
      [0, 0, 0, 0, 1, 0], 
      [0, 0, 0, 0, 0, 1]]
      
  model_params:
    # size params
    lr: 0.038
    lf: 0.052
    m: 0.181
    I: 0.000505

    # lateral force params
    Df: 0.65
    Cf: 1.5
    Bf: 5.2
    Dr: 1.0
    Cr: 1.45
    Br: 8.5

    # longitudinal force params
    Cm1: 0.98028992
    Cm2: 0.01814131
    Cd: 0.02750696
    Croll: 0.08518052

 
