/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) pacejka_model_tracking_mpc_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[12] = {8, 1, 0, 8, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s1[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s2[24] = {20, 1, 0, 20, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19};
static const casadi_int casadi_s3[14] = {10, 1, 0, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9};

/* pacejka_model_tracking_mpc_expl_vde_adj:(i0[8],i1[8],i2[2],i3[20])->(o0[10]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a3, a4, a5, a6, a7, a8, a9;
  a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[0]? arg[0][2] : 0;
  a1=cos(a0);
  a2=arg[0]? arg[0][3] : 0;
  a3=arg[1]? arg[1][1] : 0;
  a4=(a2*a3);
  a1=(a1*a4);
  a4=sin(a0);
  a5=arg[0]? arg[0][4] : 0;
  a6=(a5*a3);
  a4=(a4*a6);
  a1=(a1-a4);
  a4=cos(a0);
  a6=arg[1]? arg[1][0] : 0;
  a7=(a5*a6);
  a4=(a4*a7);
  a1=(a1-a4);
  a4=sin(a0);
  a7=(a2*a6);
  a4=(a4*a7);
  a1=(a1-a4);
  if (res[0]!=0) res[0][2]=a1;
  a1=arg[3]? arg[3][7] : 0;
  a4=arg[0]? arg[0][5] : 0;
  a7=(a1*a4);
  a7=(a7/a2);
  a8=(a7/a2);
  a9=arg[3]? arg[3][12] : 0;
  a10=arg[3]? arg[3][11] : 0;
  a11=arg[0]? arg[0][7] : 0;
  a12=(a5/a2);
  a13=atan(a12);
  a14=(a11-a13);
  a14=(a14-a7);
  a14=(a9*a14);
  a7=atan(a14);
  a7=(a10*a7);
  a15=cos(a7);
  a16=arg[3]? arg[3][10] : 0;
  a17=cos(a11);
  a18=arg[1]? arg[1][5] : 0;
  a19=arg[3]? arg[3][9] : 0;
  a18=(a18/a19);
  a17=(a17*a18);
  a17=(a1*a17);
  a19=cos(a11);
  a20=arg[1]? arg[1][4] : 0;
  a21=arg[3]? arg[3][8] : 0;
  a20=(a20/a21);
  a19=(a19*a20);
  a17=(a17+a19);
  a19=sin(a11);
  a22=arg[1]? arg[1][3] : 0;
  a22=(a22/a21);
  a19=(a19*a22);
  a17=(a17-a19);
  a17=(a16*a17);
  a15=(a15*a17);
  a10=(a10*a15);
  a15=1.;
  a14=casadi_sq(a14);
  a14=(a15+a14);
  a10=(a10/a14);
  a9=(a9*a10);
  a8=(a8*a9);
  a10=(a4*a20);
  a10=(a21*a10);
  a14=arg[3]? arg[3][6] : 0;
  a17=(a14*a4);
  a17=(a17/a2);
  a19=(a17/a2);
  a23=arg[3]? arg[3][15] : 0;
  a24=arg[3]? arg[3][14] : 0;
  a17=(a17-a13);
  a17=(a23*a17);
  a13=atan(a17);
  a13=(a24*a13);
  a13=cos(a13);
  a25=arg[3]? arg[3][13] : 0;
  a26=(a14*a18);
  a26=(a20-a26);
  a25=(a25*a26);
  a13=(a13*a25);
  a24=(a24*a13);
  a17=casadi_sq(a17);
  a17=(a15+a17);
  a24=(a24/a17);
  a23=(a23*a24);
  a19=(a19*a23);
  a10=(a10+a19);
  a8=(a8-a10);
  a10=(a12/a2);
  a19=(a23+a9);
  a12=casadi_sq(a12);
  a15=(a15+a12);
  a19=(a19/a15);
  a10=(a10*a19);
  a8=(a8+a10);
  a10=arg[3]? arg[3][18] : 0;
  a15=(a10*a2);
  a15=(a15*a22);
  a8=(a8-a15);
  a15=(a2*a22);
  a10=(a10*a15);
  a8=(a8-a10);
  a10=arg[3]? arg[3][17] : 0;
  a15=arg[0]? arg[0][6] : 0;
  a15=(a15*a22);
  a15=(a10*a15);
  a8=(a8-a15);
  a15=sin(a0);
  a15=(a15*a3);
  a8=(a8+a15);
  a15=cos(a0);
  a15=(a15*a6);
  a8=(a8+a15);
  if (res[0]!=0) res[0][3]=a8;
  a4=(a4*a22);
  a4=(a21*a4);
  a19=(a19/a2);
  a4=(a4-a19);
  a19=cos(a0);
  a19=(a19*a3);
  a4=(a4+a19);
  a0=sin(a0);
  a0=(a0*a6);
  a4=(a4-a0);
  if (res[0]!=0) res[0][4]=a4;
  a23=(a23/a2);
  a14=(a14*a23);
  a23=(a21*a2);
  a23=(a23*a20);
  a14=(a14-a23);
  a21=(a21*a5);
  a21=(a21*a22);
  a14=(a14+a21);
  a21=(a9/a2);
  a21=(a1*a21);
  a14=(a14-a21);
  a21=arg[1]? arg[1][2] : 0;
  a14=(a14+a21);
  if (res[0]!=0) res[0][5]=a14;
  a14=arg[3]? arg[3][16] : 0;
  a10=(a10*a2);
  a14=(a14-a10);
  a14=(a14*a22);
  if (res[0]!=0) res[0][6]=a14;
  a14=sin(a11);
  a7=sin(a7);
  a16=(a16*a7);
  a1=(a16*a1);
  a1=(a1*a18);
  a14=(a14*a1);
  a1=sin(a11);
  a20=(a16*a20);
  a1=(a1*a20);
  a14=(a14+a1);
  a11=cos(a11);
  a16=(a16*a22);
  a11=(a11*a16);
  a14=(a14+a11);
  a9=(a9-a14);
  if (res[0]!=0) res[0][7]=a9;
  a9=arg[1]? arg[1][6] : 0;
  if (res[0]!=0) res[0][8]=a9;
  a9=arg[1]? arg[1][7] : 0;
  if (res[0]!=0) res[0][9]=a9;
  return 0;
}

CASADI_SYMBOL_EXPORT int pacejka_model_tracking_mpc_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int pacejka_model_tracking_mpc_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int pacejka_model_tracking_mpc_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void pacejka_model_tracking_mpc_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int pacejka_model_tracking_mpc_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void pacejka_model_tracking_mpc_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void pacejka_model_tracking_mpc_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void pacejka_model_tracking_mpc_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int pacejka_model_tracking_mpc_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int pacejka_model_tracking_mpc_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real pacejka_model_tracking_mpc_expl_vde_adj_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* pacejka_model_tracking_mpc_expl_vde_adj_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* pacejka_model_tracking_mpc_expl_vde_adj_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* pacejka_model_tracking_mpc_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* pacejka_model_tracking_mpc_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int pacejka_model_tracking_mpc_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
