# Description of configuration files can be found at "https://gitlab.ethz.ch/ics-group/projects/andrea/crs-2.0/-/wikis/ros-configuration"
state_type: pacejka_car
planner_type: multi_agent_circular_planner
max_rate: 10
