/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) pacejka_model_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[13] = {9, 1, 0, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8};
static const casadi_int casadi_s1[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s2[30] = {26, 1, 0, 26, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25};
static const casadi_int casadi_s3[16] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};

/* pacejka_model_expl_vde_adj:(i0[9],i1[9],i2[3],i3[26])->(o0[12]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a3, a4, a5, a6, a7, a8, a9;
  a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  a1=arg[0]? arg[0][2] : 0;
  a2=cos(a1);
  a3=arg[0]? arg[0][3] : 0;
  a4=arg[1]? arg[1][1] : 0;
  a5=(a3*a4);
  a2=(a2*a5);
  a5=sin(a1);
  a6=arg[0]? arg[0][4] : 0;
  a7=(a6*a4);
  a5=(a5*a7);
  a2=(a2-a5);
  a5=cos(a1);
  a7=arg[1]? arg[1][0] : 0;
  a8=(a6*a7);
  a5=(a5*a8);
  a2=(a2-a5);
  a5=sin(a1);
  a8=(a3*a7);
  a5=(a5*a8);
  a2=(a2-a5);
  if (res[0]!=0) res[0][2]=a2;
  a2=arg[3]? arg[3][13] : 0;
  a5=arg[0]? arg[0][5] : 0;
  a8=(a2*a5);
  a8=(a8/a3);
  a9=(a8/a3);
  a10=arg[3]? arg[3][18] : 0;
  a11=arg[3]? arg[3][17] : 0;
  a12=arg[0]? arg[0][7] : 0;
  a13=(a6/a3);
  a14=atan(a13);
  a15=(a12-a14);
  a15=(a15-a8);
  a15=(a10*a15);
  a8=atan(a15);
  a8=(a11*a8);
  a16=cos(a8);
  a17=arg[3]? arg[3][16] : 0;
  a18=cos(a12);
  a19=arg[1]? arg[1][5] : 0;
  a20=arg[3]? arg[3][15] : 0;
  a19=(a19/a20);
  a18=(a18*a19);
  a18=(a2*a18);
  a20=cos(a12);
  a21=arg[1]? arg[1][4] : 0;
  a22=arg[3]? arg[3][14] : 0;
  a21=(a21/a22);
  a20=(a20*a21);
  a18=(a18+a20);
  a20=sin(a12);
  a23=arg[1]? arg[1][3] : 0;
  a23=(a23/a22);
  a20=(a20*a23);
  a18=(a18-a20);
  a18=(a17*a18);
  a16=(a16*a18);
  a11=(a11*a16);
  a16=1.;
  a15=casadi_sq(a15);
  a15=(a16+a15);
  a11=(a11/a15);
  a10=(a10*a11);
  a9=(a9*a10);
  a11=(a5*a21);
  a11=(a22*a11);
  a15=arg[3]? arg[3][12] : 0;
  a18=(a15*a5);
  a18=(a18/a3);
  a20=(a18/a3);
  a24=arg[3]? arg[3][21] : 0;
  a25=arg[3]? arg[3][20] : 0;
  a18=(a18-a14);
  a18=(a24*a18);
  a14=atan(a18);
  a14=(a25*a14);
  a14=cos(a14);
  a26=arg[3]? arg[3][19] : 0;
  a27=(a15*a19);
  a27=(a21-a27);
  a26=(a26*a27);
  a14=(a14*a26);
  a25=(a25*a14);
  a18=casadi_sq(a18);
  a18=(a16+a18);
  a25=(a25/a18);
  a24=(a24*a25);
  a20=(a20*a24);
  a11=(a11+a20);
  a9=(a9-a11);
  a11=(a13/a3);
  a20=(a24+a10);
  a13=casadi_sq(a13);
  a16=(a16+a13);
  a20=(a20/a16);
  a11=(a11*a20);
  a9=(a9+a11);
  a11=arg[3]? arg[3][24] : 0;
  a16=(a11*a3);
  a16=(a16*a23);
  a9=(a9-a16);
  a16=(a3*a23);
  a11=(a11*a16);
  a9=(a9-a11);
  a11=arg[3]? arg[3][23] : 0;
  a16=arg[0]? arg[0][6] : 0;
  a16=(a16*a23);
  a16=(a11*a16);
  a9=(a9-a16);
  a16=sin(a1);
  a16=(a16*a4);
  a9=(a9+a16);
  a16=cos(a1);
  a16=(a16*a7);
  a9=(a9+a16);
  if (res[0]!=0) res[0][3]=a9;
  a5=(a5*a23);
  a5=(a22*a5);
  a20=(a20/a3);
  a5=(a5-a20);
  a20=cos(a1);
  a20=(a20*a4);
  a5=(a5+a20);
  a1=sin(a1);
  a1=(a1*a7);
  a5=(a5-a1);
  if (res[0]!=0) res[0][4]=a5;
  a24=(a24/a3);
  a15=(a15*a24);
  a24=(a22*a3);
  a24=(a24*a21);
  a15=(a15-a24);
  a22=(a22*a6);
  a22=(a22*a23);
  a15=(a15+a22);
  a22=(a10/a3);
  a22=(a2*a22);
  a15=(a15-a22);
  a22=arg[1]? arg[1][2] : 0;
  a15=(a15+a22);
  if (res[0]!=0) res[0][5]=a15;
  a15=arg[3]? arg[3][22] : 0;
  a11=(a11*a3);
  a15=(a15-a11);
  a15=(a15*a23);
  if (res[0]!=0) res[0][6]=a15;
  a15=sin(a12);
  a8=sin(a8);
  a17=(a17*a8);
  a2=(a17*a2);
  a2=(a2*a19);
  a15=(a15*a2);
  a2=sin(a12);
  a21=(a17*a21);
  a2=(a2*a21);
  a15=(a15+a2);
  a12=cos(a12);
  a17=(a17*a23);
  a12=(a12*a17);
  a15=(a15+a12);
  a10=(a10-a15);
  if (res[0]!=0) res[0][7]=a10;
  if (res[0]!=0) res[0][8]=a0;
  a0=arg[1]? arg[1][6] : 0;
  if (res[0]!=0) res[0][9]=a0;
  a0=arg[1]? arg[1][7] : 0;
  if (res[0]!=0) res[0][10]=a0;
  a0=arg[1]? arg[1][8] : 0;
  if (res[0]!=0) res[0][11]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int pacejka_model_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int pacejka_model_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int pacejka_model_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void pacejka_model_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int pacejka_model_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void pacejka_model_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void pacejka_model_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void pacejka_model_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int pacejka_model_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int pacejka_model_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real pacejka_model_expl_vde_adj_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* pacejka_model_expl_vde_adj_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* pacejka_model_expl_vde_adj_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* pacejka_model_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* pacejka_model_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int pacejka_model_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
