/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) pacejka_model_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[13] = {9, 1, 0, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8};
static const casadi_int casadi_s1[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s2[24] = {20, 1, 0, 20, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19};
static const casadi_int casadi_s3[13] = {12, 1, 0, 9, 2, 3, 4, 5, 6, 7, 9, 10, 11};

/* pacejka_model_expl_vde_adj:(i0[9],i1[9],i2[3],i3[20])->(o0[12x1,9nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2, *w3=w+3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22, w23, w24, w25, w26, w27, w28, w29;
  /* #0: @0 = input[0][2] */
  w0 = arg[0] ? arg[0][2] : 0;
  /* #1: @1 = cos(@0) */
  w1 = cos( w0 );
  /* #2: @2 = input[0][3] */
  w2 = arg[0] ? arg[0][3] : 0;
  /* #3: @3 = input[1][0] */
  casadi_copy(arg[1], 9, w3);
  /* #4: {@4, @5, @6, @7, @8, @9, @10, @11, @12} = vertsplit(@3) */
  w4 = w3[0];
  w5 = w3[1];
  w6 = w3[2];
  w7 = w3[3];
  w8 = w3[4];
  w9 = w3[5];
  w10 = w3[6];
  w11 = w3[7];
  w12 = w3[8];
  /* #5: @13 = (@2*@5) */
  w13  = (w2*w5);
  /* #6: @1 = (@1*@13) */
  w1 *= w13;
  /* #7: @13 = sin(@0) */
  w13 = sin( w0 );
  /* #8: @14 = input[0][4] */
  w14 = arg[0] ? arg[0][4] : 0;
  /* #9: @15 = (@14*@5) */
  w15  = (w14*w5);
  /* #10: @13 = (@13*@15) */
  w13 *= w15;
  /* #11: @1 = (@1-@13) */
  w1 -= w13;
  /* #12: @13 = cos(@0) */
  w13 = cos( w0 );
  /* #13: @15 = (@14*@4) */
  w15  = (w14*w4);
  /* #14: @13 = (@13*@15) */
  w13 *= w15;
  /* #15: @1 = (@1-@13) */
  w1 -= w13;
  /* #16: @13 = sin(@0) */
  w13 = sin( w0 );
  /* #17: @15 = (@2*@4) */
  w15  = (w2*w4);
  /* #18: @13 = (@13*@15) */
  w13 *= w15;
  /* #19: @1 = (@1-@13) */
  w1 -= w13;
  /* #20: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  /* #21: @1 = input[3][6] */
  w1 = arg[3] ? arg[3][6] : 0;
  /* #22: @13 = input[0][5] */
  w13 = arg[0] ? arg[0][5] : 0;
  /* #23: @15 = (@1*@13) */
  w15  = (w1*w13);
  /* #24: @15 = (@15/@2) */
  w15 /= w2;
  /* #25: @16 = (@15/@2) */
  w16  = (w15/w2);
  /* #26: @17 = input[3][15] */
  w17 = arg[3] ? arg[3][15] : 0;
  /* #27: @18 = input[3][14] */
  w18 = arg[3] ? arg[3][14] : 0;
  /* #28: @19 = (@14/@2) */
  w19  = (w14/w2);
  /* #29: @20 = atan(@19) */
  w20 = atan( w19 );
  /* #30: @15 = (@15-@20) */
  w15 -= w20;
  /* #31: @15 = (@17*@15) */
  w15  = (w17*w15);
  /* #32: @21 = atan(@15) */
  w21 = atan( w15 );
  /* #33: @21 = (@18*@21) */
  w21  = (w18*w21);
  /* #34: @21 = cos(@21) */
  w21 = cos( w21 );
  /* #35: @22 = input[3][13] */
  w22 = arg[3] ? arg[3][13] : 0;
  /* #36: @23 = input[3][8] */
  w23 = arg[3] ? arg[3][8] : 0;
  /* #37: @8 = (@8/@23) */
  w8 /= w23;
  /* #38: @24 = input[3][9] */
  w24 = arg[3] ? arg[3][9] : 0;
  /* #39: @9 = (@9/@24) */
  w9 /= w24;
  /* #40: @24 = (@1*@9) */
  w24  = (w1*w9);
  /* #41: @24 = (@8-@24) */
  w24  = (w8-w24);
  /* #42: @22 = (@22*@24) */
  w22 *= w24;
  /* #43: @21 = (@21*@22) */
  w21 *= w22;
  /* #44: @18 = (@18*@21) */
  w18 *= w21;
  /* #45: @21 = 1 */
  w21 = 1.;
  /* #46: @15 = sq(@15) */
  w15 = casadi_sq( w15 );
  /* #47: @21 = (@21+@15) */
  w21 += w15;
  /* #48: @18 = (@18/@21) */
  w18 /= w21;
  /* #49: @17 = (@17*@18) */
  w17 *= w18;
  /* #50: @16 = (@16*@17) */
  w16 *= w17;
  /* #51: @16 = (-@16) */
  w16 = (- w16 );
  /* #52: @18 = (@13*@8) */
  w18  = (w13*w8);
  /* #53: @18 = (@23*@18) */
  w18  = (w23*w18);
  /* #54: @16 = (@16-@18) */
  w16 -= w18;
  /* #55: @18 = input[3][7] */
  w18 = arg[3] ? arg[3][7] : 0;
  /* #56: @21 = (@18*@13) */
  w21  = (w18*w13);
  /* #57: @21 = (@21/@2) */
  w21 /= w2;
  /* #58: @15 = (@21/@2) */
  w15  = (w21/w2);
  /* #59: @22 = input[3][12] */
  w22 = arg[3] ? arg[3][12] : 0;
  /* #60: @24 = input[3][11] */
  w24 = arg[3] ? arg[3][11] : 0;
  /* #61: @25 = input[0][7] */
  w25 = arg[0] ? arg[0][7] : 0;
  /* #62: @20 = (@25-@20) */
  w20  = (w25-w20);
  /* #63: @20 = (@20-@21) */
  w20 -= w21;
  /* #64: @20 = (@22*@20) */
  w20  = (w22*w20);
  /* #65: @21 = atan(@20) */
  w21 = atan( w20 );
  /* #66: @21 = (@24*@21) */
  w21  = (w24*w21);
  /* #67: @26 = cos(@21) */
  w26 = cos( w21 );
  /* #68: @27 = input[3][10] */
  w27 = arg[3] ? arg[3][10] : 0;
  /* #69: @28 = cos(@25) */
  w28 = cos( w25 );
  /* #70: @28 = (@28*@9) */
  w28 *= w9;
  /* #71: @28 = (@18*@28) */
  w28  = (w18*w28);
  /* #72: @29 = cos(@25) */
  w29 = cos( w25 );
  /* #73: @29 = (@29*@8) */
  w29 *= w8;
  /* #74: @28 = (@28+@29) */
  w28 += w29;
  /* #75: @29 = sin(@25) */
  w29 = sin( w25 );
  /* #76: @7 = (@7/@23) */
  w7 /= w23;
  /* #77: @29 = (@29*@7) */
  w29 *= w7;
  /* #78: @28 = (@28-@29) */
  w28 -= w29;
  /* #79: @28 = (@27*@28) */
  w28  = (w27*w28);
  /* #80: @26 = (@26*@28) */
  w26 *= w28;
  /* #81: @24 = (@24*@26) */
  w24 *= w26;
  /* #82: @26 = 1 */
  w26 = 1.;
  /* #83: @20 = sq(@20) */
  w20 = casadi_sq( w20 );
  /* #84: @26 = (@26+@20) */
  w26 += w20;
  /* #85: @24 = (@24/@26) */
  w24 /= w26;
  /* #86: @22 = (@22*@24) */
  w22 *= w24;
  /* #87: @15 = (@15*@22) */
  w15 *= w22;
  /* #88: @16 = (@16+@15) */
  w16 += w15;
  /* #89: @15 = (@19/@2) */
  w15  = (w19/w2);
  /* #90: @24 = (-@22) */
  w24 = (- w22 );
  /* #91: @24 = (@24-@17) */
  w24 -= w17;
  /* #92: @26 = 1 */
  w26 = 1.;
  /* #93: @19 = sq(@19) */
  w19 = casadi_sq( w19 );
  /* #94: @26 = (@26+@19) */
  w26 += w19;
  /* #95: @24 = (@24/@26) */
  w24 /= w26;
  /* #96: @15 = (@15*@24) */
  w15 *= w24;
  /* #97: @16 = (@16-@15) */
  w16 -= w15;
  /* #98: @15 = input[3][18] */
  w15 = arg[3] ? arg[3][18] : 0;
  /* #99: @26 = (@15*@2) */
  w26  = (w15*w2);
  /* #100: @26 = (@26*@7) */
  w26 *= w7;
  /* #101: @16 = (@16-@26) */
  w16 -= w26;
  /* #102: @26 = (@2*@7) */
  w26  = (w2*w7);
  /* #103: @15 = (@15*@26) */
  w15 *= w26;
  /* #104: @16 = (@16-@15) */
  w16 -= w15;
  /* #105: @15 = input[3][17] */
  w15 = arg[3] ? arg[3][17] : 0;
  /* #106: @26 = input[0][6] */
  w26 = arg[0] ? arg[0][6] : 0;
  /* #107: @26 = (@26*@7) */
  w26 *= w7;
  /* #108: @26 = (@15*@26) */
  w26  = (w15*w26);
  /* #109: @16 = (@16-@26) */
  w16 -= w26;
  /* #110: @26 = sin(@0) */
  w26 = sin( w0 );
  /* #111: @26 = (@26*@5) */
  w26 *= w5;
  /* #112: @16 = (@16+@26) */
  w16 += w26;
  /* #113: @26 = cos(@0) */
  w26 = cos( w0 );
  /* #114: @26 = (@26*@4) */
  w26 *= w4;
  /* #115: @16 = (@16+@26) */
  w16 += w26;
  /* #116: output[0][1] = @16 */
  if (res[0]) res[0][1] = w16;
  /* #117: @13 = (@13*@7) */
  w13 *= w7;
  /* #118: @13 = (@23*@13) */
  w13  = (w23*w13);
  /* #119: @24 = (@24/@2) */
  w24 /= w2;
  /* #120: @13 = (@13+@24) */
  w13 += w24;
  /* #121: @24 = cos(@0) */
  w24 = cos( w0 );
  /* #122: @24 = (@24*@5) */
  w24 *= w5;
  /* #123: @13 = (@13+@24) */
  w13 += w24;
  /* #124: @0 = sin(@0) */
  w0 = sin( w0 );
  /* #125: @0 = (@0*@4) */
  w0 *= w4;
  /* #126: @13 = (@13-@0) */
  w13 -= w0;
  /* #127: output[0][2] = @13 */
  if (res[0]) res[0][2] = w13;
  /* #128: @17 = (@17/@2) */
  w17 /= w2;
  /* #129: @1 = (@1*@17) */
  w1 *= w17;
  /* #130: @17 = (@23*@2) */
  w17  = (w23*w2);
  /* #131: @17 = (@17*@8) */
  w17 *= w8;
  /* #132: @1 = (@1-@17) */
  w1 -= w17;
  /* #133: @23 = (@23*@14) */
  w23 *= w14;
  /* #134: @23 = (@23*@7) */
  w23 *= w7;
  /* #135: @1 = (@1+@23) */
  w1 += w23;
  /* #136: @23 = (@22/@2) */
  w23  = (w22/w2);
  /* #137: @23 = (@18*@23) */
  w23  = (w18*w23);
  /* #138: @1 = (@1-@23) */
  w1 -= w23;
  /* #139: @1 = (@1+@6) */
  w1 += w6;
  /* #140: output[0][3] = @1 */
  if (res[0]) res[0][3] = w1;
  /* #141: @1 = input[3][16] */
  w1 = arg[3] ? arg[3][16] : 0;
  /* #142: @15 = (@15*@2) */
  w15 *= w2;
  /* #143: @1 = (@1-@15) */
  w1 -= w15;
  /* #144: @1 = (@1*@7) */
  w1 *= w7;
  /* #145: output[0][4] = @1 */
  if (res[0]) res[0][4] = w1;
  /* #146: @1 = sin(@25) */
  w1 = sin( w25 );
  /* #147: @21 = sin(@21) */
  w21 = sin( w21 );
  /* #148: @27 = (@27*@21) */
  w27 *= w21;
  /* #149: @8 = (@27*@8) */
  w8  = (w27*w8);
  /* #150: @1 = (@1*@8) */
  w1 *= w8;
  /* #151: @1 = (-@1) */
  w1 = (- w1 );
  /* #152: @8 = sin(@25) */
  w8 = sin( w25 );
  /* #153: @18 = (@27*@18) */
  w18  = (w27*w18);
  /* #154: @18 = (@18*@9) */
  w18 *= w9;
  /* #155: @8 = (@8*@18) */
  w8 *= w18;
  /* #156: @1 = (@1-@8) */
  w1 -= w8;
  /* #157: @25 = cos(@25) */
  w25 = cos( w25 );
  /* #158: @27 = (@27*@7) */
  w27 *= w7;
  /* #159: @25 = (@25*@27) */
  w25 *= w27;
  /* #160: @1 = (@1-@25) */
  w1 -= w25;
  /* #161: @1 = (@1+@22) */
  w1 += w22;
  /* #162: output[0][5] = @1 */
  if (res[0]) res[0][5] = w1;
  /* #163: output[0][6] = @10 */
  if (res[0]) res[0][6] = w10;
  /* #164: output[0][7] = @11 */
  if (res[0]) res[0][7] = w11;
  /* #165: output[0][8] = @12 */
  if (res[0]) res[0][8] = w12;
  return 0;
}

CASADI_SYMBOL_EXPORT int pacejka_model_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int pacejka_model_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int pacejka_model_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void pacejka_model_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int pacejka_model_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void pacejka_model_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void pacejka_model_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void pacejka_model_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int pacejka_model_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int pacejka_model_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real pacejka_model_expl_vde_adj_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* pacejka_model_expl_vde_adj_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* pacejka_model_expl_vde_adj_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* pacejka_model_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* pacejka_model_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int pacejka_model_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 10;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 38;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
